#!/usr/bin/env bash
# Transfers file to server
if [$# lt 3]
then
	echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
else
	scp -o StrictHostKeyChecking=no username1@source_host:directory1/filename1 username2@destination_host:directory2/filename2
fi