#!/usr/bin/env bash
# Installs nginx with redirection
sudo apt-get -y update
sudo apt-get -y install nginx
echo "Holberton School" | sudo tee /var/www/html/index.html
info="\tlocation \/redirect_me {\n\t\treturn 301 https://www.buzzfeed.com/angelospagnolo/ultimate-frasier-trivia-quiz;\n\t};"
sed -r -i "s/server_name _;/$info/" /etc/nginx/sites-available/default
sudo service nginx restart
