#!/usr/bin/env bash
#Installs nginx with redirection
sudo apt-get -y update
sudo apt-get -y install nginx
echo "Holberton School" | sudo tee /var/www/html/index.html
sudo echo "Ceci n'est pas une page" | sudo tee /var/www/html/custom_404.html
redir="\terror_page 404 /custom_404.html;\n\tlocation /custom_404.html {\n\t\troot /var/www/html;\n\t\tinternal;}"
sudo sed -r -i "/server_name .+;/a\ $redir" /etc/nginx/sites-available/default
sudo service nginx restart
