#!/usr/bin/env bash
# cobfiguresload balancer on new server
apt update
apt install -y haproxy
echo -e '
frontend incoming_https
\tbind \*:80
\tdefault_backend web_servers

backend web_servers
\tbalance roundrobin
\tserver 2496-web-01 35.229.48.31
\tserver 2496-web-02 54.242.149.19' | tee -a /etc/haproxy/haproxy.cfg
service haproxy restart
