#!/usr/bin/env bash
#Creates infinite loop that only ends with SIGQUIT or SIGTERM

su echo $$ > /var/run/holbertonscript.pid
trap "echo 'I hate the kill command'; rm /var/run/holbertonscript.pid; exit" TERM
trap "rm /var/run/holbertonscript.pid; exit" QUIT
trap "echo 'Y U no love me?!'" INT

while :
do
	echo "To infinity and beyond"
    	sleep 2
done
