#!/usr/bin/env bash
# runs nginx as user nginx and listens on port 8080
sudo apt-get update
sudo apt-get -y install apache2
apt-get update
apt-get -y install nginx
sudo service apache2 start
# add or change 'user nginx' in /etc/nginx/nginx.conf
# apache was still running as www-data
sudo pkill -f apache
# change permissions so we can edit
chmod 700 /etc/nginx/nginx.conf
# add user to nginx config - default www-data already commented out
#sed -i '1i user nginx;' /etc/nginx/nginx.conf
sudo chown -R nginx:nginx /etc/nginx/nginx.conf
# listen on port 8080
sed -i 's/80/8080/' /etc/nginx/sites-available/default
# restart as user nginx
sudo -u nginx service nginx restart
