#!/usr/bin/env bash
# runs nginx as user nginx and listens on port 8080

# add or change 'user nginx' in /etc/nginx/nginx.conf
# apache was still running as www-data
sudo pkill -f apache
# change permissions so we can edit
chmod 700 /etc/nginx/nginx.conf
# add user to nginx config - default www-data already commented out
sed -i '1i user nginx;' /etc/nginx/nginx.conf
# listen on port 8080
sed -i 's/80/8080/' /etc/nginx/sites-available/default
# restart as user nginx
sudo -u nginx service nginx restart
