#!/usr/bin/env bash
# runs nginx as nginx and listens on port 8080
sudo pkill -f apache
sudo chown -R nginx:nginx /etc/nginx/nginx.conf
chmod 700 /etc/nginx/nginx.conf
sed -i 's/80/8080/' /etc/nginx/sites-available/default
sudo -u nginx service nginx restart
