#!/usr/bin/env bash
# runs nginx as user nginx and listens on port 8080
sudo pkill apache
chmod 700 /etc/nginx/nginx.conf
sudo sed -i '1i user nginx;' /etc/nginx/nginx.conf
sudo sed -i 's/80/8080/' /etc/nginx/sites-available/default
sudo -u nginx service nginx restart
